### PR TITLE
Improvement/cldsrv 237 revert tagging

### PR DESCRIPTION
**Pull request by ghost**
Commits reverted:

- 4b4f35d36f71da4b4cc76f56b26e837c072972e9: CLDSRV-167: implement put bucket tagging
- ea107a50e15842ac0a046b10bcb55ff4bc2e773d: CLDSRV-167: Implement bucket owner check and change check order
- 66110ad2ac132818f31b9f515f13d300f788e77a: Update bucketPutTagging.js
- 8729f86db06702694a7972ada52207677e40e65b: CLDSRV-168: add deleteBucketTagging
- 63ae80e76e3be63f0736506dcc7f9f0d4f020c5d: CLDSRV-169: add getBucketTagging
- 3e83c7d836fd04c59c778dce0bc13ffcb3c79700: CLDSRV-169: bucket tagging tests

Changes retained: 
- Arsenal package bump
- Dockerfile `network-concurrency=1` on `RUN yarn cache clean` 
- yarn.lock

### CODE REVIEW

**Review by anurag4DSB — COMMENTED** [review]
PR LGTM just that we should not have yarn.lock changes. :)

**Review by anurag4DSB — APPROVED** [review]

**Review by XinLi0207 — APPROVED** [review]

**Pull request merged**
