### PR TITLE
Feature/zenko 551 mutliple backend tests

### PR DESCRIPTION
**Pull request by ssalaues**
Multiple backend test, mvn, and spec tests (men backend) on Eve

### CODE REVIEW

**Review by giacope — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]
LGTM

**Review by tcarmet — APPROVED** [review]

**Comment by tcarmet** [comment]
Bert-E is reporting that the dev branches are not self contained
made a pull request to fix this
https://github.com/scality/S3/pull/1297

**Comment by tcarmet** [comment]
ping

**Comment by tcarmet** [comment]
UHUL

**Pull request merged**
