### PR TITLE
CLDSRV-468:CLDSRV version bump

### PR DESCRIPTION
**Pull request by benzekrimaha**
This PR is linked to this ticket : https://scality.atlassian.net/browse/CLDSRV-468 and is aiming to update the version for a release to be done enabling a federation PR to be open ( the bump is only on this branch , no version bump will be done on the integration branches )

### CODE REVIEW

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
@bert-e create_pull_requests

**Review by nicolas2bert — APPROVED** [review]

**Review by KillianG — APPROVED** [review]

**Pull request merged**
