### PR TITLE
[CLDSRV-388] ✨ Implement GHAS

### PR DESCRIPTION
**Pull request by gaspardmoindrot**
# Pull request template

### Motivation and context

In the interest of security, it is important, even essential, to regularly perform code and image scans to identify any security vulnerabilities. In line with this, the changes made in this PR will enable the implementation of GitHub Advanced Security principles within this repository. This includes the implementation of workflow files that allow performing regular scans.

### Related issues

None

### Add tests to cover the changes

No tests to add since it's only workflow files, it doesn't directly impact the code.

### Sign your work

Signed-off-by: Gaspard Moindrot <gaspard.moindrot@scality.com>

### CODE REVIEW

**Comment by gaspardmoindrot** [comment]
`ping`

**Comment by gaspardmoindrot** [comment]
`ping`

**Review by tcarmet — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]
LGTM, to be checked if development/7.4 is the right target

**Pull request merged**
