### PR TITLE
CLDSRV-228: bump version to 7.10.3

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by XinLi0207 — APPROVED** [review]

**Review by ghost — COMMENTED** [review]
Please make sure to target the right branch and add the fix versions in the ticket, so that we can review the integration PRs where you should revert the changes for the 8.x branches :slightly_smiling_face:

**Review by ghost — CHANGES_REQUESTED** [review]
Blocking for now (ping me once it's done and I will approve right away!)

**Comment by ghost** [comment]
ping

**Review by KillianG — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
