### PR TITLE
improvement: S3C-3044-update-arsenal-hash

### PR DESCRIPTION
**Pull request by anurag4DSB**
## Description
Updates arsenal hash for audit logs: https://github.com/scality/Arsenal/pull/1099

### Motivation and context
Audit logs needed https://scality.atlassian.net/browse/S3C-2675

### Why is this change required? What problem does it solve?
Request from Amadeus for logs in Leef format. This PR just adds log fields without adding extra log lines.

### Related issues
https://github.com/scality/Arsenal/pull/1099

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by ilkescality — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Comment by rahulreddy** [comment]
@anurag4DSB This is going to have problems. In your 7.7, 7.8, 8.1 and 8.2 integration branches you are not using the commit hash of their respective branch in Arsenal.
With the changes in this PR when yarn/npm pull the Arsenal dependency, it could pull the commit from any of the branches leading to the issues that both you and @ilkescality ran into earlier.
Edit: To make my point clearer
Cloudserver 7.4 should use https://github.com/scality/Arsenal/commits/development/7.4 - `2b23c0d55978973a56b910f1c8c80eae915d11de`
7.7 should use the merge commit from https://github.com/scality/Arsenal/commits/development/7.7  `6530f0ace443ec6f553ea4832c8bf3d044e5f66e`
7.8 should use the merge commit https://github.com/scality/Arsenal/commits/development/7.8  `6530f0ace443ec6f553ea4832c8bf3d044e5f66e`
8.1 should use the merge commit  https://github.com/scality/Arsenal/commits/development/8.1 `b4b5712df7953b0f34cab2234e2f284c19c121b1`
8.2 should use the merge commit  - well since 8.2 doesn't exist you can use 8.1 hash

**Comment by ilkescality** [comment]
@rahulreddy I'm a bit confused about commit hash of integration branches, I looked into integration PRs while approving and verified that the Arsenal hashes are what they're supposed to be (and seem the same as what you wrote):

Integration PR for 8.2 with Arsenal b4b5712 https://github.com/scality/cloudserver/pull/2678/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L22

Integration PR for 8.1 with Arsenal b4b5712 https://github.com/scality/cloudserver/pull/2677/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22

Integration PR for 7.8 with Arsenal 6530f0a https://github.com/scality/cloudserver/pull/2676/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22

Integration PR for 7.7 with Arsenal 6530f0a https://github.com/scality/cloudserver/pull/2675/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R22

So far I thought the correct thing (at least for this PR, assuming the aim is to update the hash for 7.4) was to keep the Arsenal hash of integration branches of this PR unchanged as they're already the latest version. Not sure if I'm missing something...

**Comment by anurag4DSB** [comment]
@rahulreddy I originally had the right commit hashes in the integration. Post i opened this PR arsenal hash has been updated by other PRs. 7.7 onwards.
I have verified each development branch has the right hash.

8.2:
https://github.com/scality/cloudserver/blob/development/8.2/package.json#L22
hash in package json:   "arsenal": "github:scality/Arsenal#b4b5712",
Arsenal has this as the latest hash: https://github.com/scality/Arsenal/commits/development/8.1L b4b5712df7953b0f34cab2234e2f284c19c121b1

And I have verified it for 8.1, 7.8, 7.7 as well.
Only 7.4 is left :)

**Comment by rahulreddy** [comment]
> And I have verified it for 8.1, 7.8, 7.7 as well.

Ok cool, thanks for checking

**Pull request merged**
