### PR TITLE
CLDSRV-420 Backport lifecycle listing

### PR DESCRIPTION
**Pull request by nicolas2bert**
Backport: 
- [CLDSRV-314](https://scality.atlassian.net/browse/CLDSRV-314) [Implement listLifecycleCurrents](https://github.com/scality/cloudserver/commit/6d0154f5eeeb92bad8ddf85e62f10b420f55aee6) **Already Reviewed**
- [CLDSRV-316](https://scality.atlassian.net/browse/CLDSRV-316) [Implement listLifecycleNonCurrents](https://github.com/scality/cloudserver/commit/25102dabf6fae2f5a934ff1faa747f668f844a64) **Already Reviewed**
- [CLDSRV-317](https://scality.atlassian.net/browse/CLDSRV-317) [Implement listLifecycleOrphans](https://github.com/scality/cloudserver/commit/640f3a9635c488ac33b4d5eee4dd8fccfbf8a489) **Already Reviewed**
- [CLDSRV-363](https://scality.atlassian.net/browse/CLDSRV-363) [ETag instead of Etag for lifecycle listings Contents](https://github.com/scality/cloudserver/commit/88b15f6caff41abf7500bd3645dfce243480f6a0) **Already Reviewed**
- [CLDSRV-366](https://scality.atlassian.net/browse/CLDSRV-366) [Clear list orphan delete markers response](https://github.com/scality/cloudserver/commit/453497c67540eaac5d9a1c58ca0f473ee0a23a97) **Already Reviewed**
- [CLDSRV-371](https://scality.atlassian.net/browse/CLDSRV-371) [ETag should be surrounded by double quotes](https://github.com/scality/cloudserver/commit/cfe139d0aa3889e22d85723b3971059271d1ac51) **Already Reviewed**
- [CLDSRV-372](https://scality.atlassian.net/browse/CLDSRV-372) [Current lifecycle versions should include version id](https://github.com/scality/cloudserver/commit/f82faacd96288f0d9f4e0bfb2975fd5b0b9fbd2a) **Already Reviewed**
- [CLDSRV-375](https://scality.atlassian.net/browse/CLDSRV-375) [Exclude already transitioned keys from lifecycle listings](https://github.com/scality/cloudserver/commit/fa46e27cad97ae492ce4293298ddd102ba1fa476) **Already Reviewed**
- [CLDSRV-412](https://scality.atlassian.net/browse/CLDSRV-412) [Test null version in Lifecycle list of non-current versions](https://github.com/scality/cloudserver/commit/782f3c7762d4cebc47d330626284b646a8b6ea1a) **Already Reviewed**

Additional work to be reviewed:
- [CLDSRV-420](https://scality.atlassian.net/browse/CLDSRV-420) [test v1 and v0 bucket format](https://github.com/scality/cloudserver/pull/5268/commits/aa04d23e68924d790c9736b688f3bbe76404ea64) Initially, the tests only covered MongoDB metadata using "v1 bucket format." Now, they include all metadata backends (file and MongoDB) and both v0 and v1 bucket formats.
- [CLDSRV-420](https://scality.atlassian.net/browse/CLDSRV-420) [add us-east-2 location](https://github.com/scality/cloudserver/pull/5268/commits/678995910985a55a9b5d29d5f151e2f32b532409) `us-east-2` location is used to test the `excluded-data-store-name` parameter.

[CLDSRV-314]: https://scality.atlassian.net/browse/CLDSRV-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLDSRV-316]: https://scality.atlassian.net/browse/CLDSRV-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLDSRV-317]: https://scality.atlassian.net/browse/CLDSRV-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLDSRV-363]: https://scality.atlassian.net/browse/CLDSRV-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLDSRV-366]: https://scality.atlassian.net/browse/CLDSRV-366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CLDSRV-371]: https://scality.atlassian.net/browse/CLDSRV-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by nicolas2bert** [comment]
ping

**Review by anurag4DSB — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by nicolas2bert** [comment]
@bert-e force_reset

**Review by KazToozs — APPROVED** [review]
LGTM

**Review by KazToozs — APPROVED** [review]

**Review by francoisferrand — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
