### PR TITLE
bf: CLDSRV-15 use updated vaultclient

### PR DESCRIPTION
**Pull request by naren-rajendran**
use updated vault client with the fix setting us-east-1 as default region when region is not provided.

### CODE REVIEW

**Review by anurag4DSB — COMMENTED** [review]
There is a conflict.
We need green builds for 8.x as well with the respective 8.x hash of Vaultclient.

**Review by nicolas2bert — APPROVED** [review]

**Review by alexanderchan-scality — APPROVED** [review]

**Comment by naren-rajendran** [comment]
@bert-e status

**Comment by naren-rajendran** [comment]
@bert-e status

**Pull request merged**
