### PR TITLE
CLDSRV-49 handle metadataSearch before implementation

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Comment by nicolas2bert** [comment]
@bert-e reset

**Comment by nicolas2bert** [comment]
@bert-e force_reset

**Comment by nicolas2bert** [comment]
ping

**Review by ghost — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
