### PR TITLE
ft: ZENKO-1186 stalled sanity check

### PR DESCRIPTION
**Pull request by alexanderchan-scality**

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@bert-e wait

**Review by anurag4DSB — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Review by philipyoo — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e wait

**Comment by alexanderchan-scality** [comment]
@bert-e reset

**Pull request merged**
