### PR TITLE
Do not parse list entries from MD6.4.7

### PR DESCRIPTION
**Pull request by MathieuCassagne**

### CODE REVIEW

**Comment by MathieuCassagne** [comment]
@bert-e reset

**Comment by MathieuCassagne** [comment]
@bert-e help

**Review by ghost — APPROVED** [review]
LGTM, backwards compat is achieved by testing the entry.value's type before going further.

Good thing it was this simple to address within S3, but I'm not very confortable on having that here, as opposed to having that in the S3C-MD backend (that may be in arsenal?).

**Comment by ghost** [comment]
As I'm unclear yet about what change/piece-of-code is at the source of this compatibliity issue, I cannot tell where the best spot to fix it would be.

**Review by lamphamsy — APPROVED** [review]

**Comment by DavidPineauScality** [comment]
@bert-e bypass_leader_approval

**Comment by tcarmet** [comment]
@bert-e bypass_leader_approval

**Pull request merged**
