### PR TITLE
[BACKPORT 7.10] CLDSRV-196: create new werelogs object over using global werelogs

### PR DESCRIPTION
**Pull request by tmacro**
(cherry picked from commit 7fd547db243c5e39de8746719a1a1157cb6534a6)

### CODE REVIEW

**Review by jonathan-gramain — COMMENTED** [review]
Sorry I don't understand what this PR is supposed to do, I believe it's indeed supposed to be a backport to 7.10 but the target branch is `development/8.7`

**Comment by jonathan-gramain** [comment]
I read more context on Slack, so indeed the target branch should be `development/7.10`

**Comment by tmacro** [comment]
@jonathan-gramain I targeted the wrong branch when I recreated with the new ticket

**Review by jonathan-gramain — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
