### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mhajder**
Correcting links.

### CODE REVIEW

**Review by bennettbuchanan — APPROVED** [review]

**Comment by rahulreddy** [comment]
@Rzeszow Our CI pipeline currently requires a Jira issue in the PR branch. Let me open a PR with these changes and add you as an Author.

**Comment by mhajder** [comment]
@rahulreddy Ok, do what you want and what you need.

**Comment by mhajder** [comment]
@bennettbuchanan @rahulreddy recall

**Comment by rahulreddy** [comment]
@mhajder Sorry for the late response, we have to close this PR without merging the changes are we changed the README and the changes are no longer relevant.

**Pull request closed without merging**
