### PR TITLE
ft: add no_proxy environment variables

### PR DESCRIPTION
**Pull request by giacope**
Same as #1268, but with bert-e.

### CODE REVIEW

**Review by ssalaues — APPROVED** [review]

**Review by philipyoo — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e help

**Comment by rahulreddy** [comment]
@bert-e bypass_build_status

**Comment by rahulreddy** [comment]
@bert-e clear

**Comment by rahulreddy** [comment]
@bert-e force_reset

**Comment by giacope** [comment]
@bert-e force_reset

**Comment by rahulreddy** [comment]
@bert-e force_reset

**Comment by rahulreddy** [comment]
@bert-e status

**Comment by rahulreddy** [comment]
@bert-e clear

**Pull request merged**
