### PR TITLE
AbortMPU writes an empty object with isAborted and uploadId set

### PR DESCRIPTION
**Pull request by tmacro**
# Pull request template

### Motivation and context

Why is this change required? What problem does it solve?

### Related issues

Please use the following link syntaxes #600 to reference issues in the
current repository

### Add tests to cover the changes

New tests added or existing tests modified to cover all changes

### Sign your work

In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

Thank you again for contributing! We will try to test and integrate the change
as soon as we can.

### CODE REVIEW

**Review by jonathan-gramain — COMMENTED** [review]
At first glance, looks good to me, but we need to be careful about keeping any existing object (MPU or not), since the abortMPU applies to an MPU in progress, not on a validated object that may already exist with the same key. That's why we use a conditional PUT, just for reference.

As we discussed the need to create a stub request is not ideal but if it solves the issue, we can keep it.

**Comment by tmacro** [comment]
Ah, so for preexisting objects only the `isAborted` and `uploadId` flags should be updated, rather than writing a new object?

**Comment by jonathan-gramain** [comment]
@tmacro there seems to be an overlook in the proposal that is described in the ticket, because we should be able to abort a *new* MPU on top of an existing, valid object (MPU or non-MPU). It is not obvious because on non-versioned buckets we only store a single entry per object, where as Vianney mentioned, ideally we should deal with this issue by versioning. But it should be doable anyway.

Here's a suggestion, @vrancurel can you please review it as well? The main difference with the original design is that we add a new field `abortedUploadId` that we can keep along with an `uploadId` instead of replacing it.

- `abortMPU`: send a special PUT request containing a single field: `abortedUploadId`. Four cases to handle in metadata (to ensure atomicity):
  - if an object already exists that is either a non-MPU or an MPU which **`uploadId` does not match the `abortedUploadId`**, **merge** the `abortedUploadId` into the existing metadata of the object. If there is already an `abortedUploadId`, then overwrite it with the new value. Return success.
  - if an object already exists that is an MPU which **`uploadId` matches the `abortedUploadId`**, **replace** the whole object metadata by a special abort placeholder (see next case). Return success.
  - if **no object exists**, **create** a special placeholder value `{"isAbort": true, "abortedUploadId": "someUploadId"}`, like already planned. This entry must be ignored on GET and listings. Return success.
  - if an `"isAbort": true` entry is already there i.e. **an abort placeholder exists**, **replace** its `abortedUploadId` with the new value. Return success
- `completeMPU`: do a conditional PUT on the object, with the following condition:
  - if no object exists, do the PUT and return success
  - if an object exists, whether it's a regular object or a `isAbort` placeholder, check its `abortedUploadId` value.
    -  If there is no `abortedUploadId` or if it is different than the `uploadId` of the MPU to complete, do the PUT and return success
    - if the `abortedUploadId` matches the `uploadId` of the object to complete, fail the condition check and return a precondition check error. Cloudserver should return the same error than when trying to complete a MPU with an invalid uploadID

**Comment by vrancurel** [comment]
The suggestion looks good to me. Please be careful that for versioned buckets we have to update 2 objects: the lastVersion and the master, but normally the condition / merge logic shall be before the double update in Repd.

**Pull request closed without merging**
