### PR TITLE
update arsenal version

### PR DESCRIPTION
**Pull request by alexandre-merle**
Update arsenal version after https://github.com/scality/Arsenal/pull/1334

### CODE REVIEW

**Comment by alexandre-merle** [comment]
@bert-e reset

**Comment by alexandre-merle** [comment]
ping

**Comment by alexandre-merle** [comment]
@bert-e reset

**Comment by alexandre-merle** [comment]
@bert-e force_reset

**Comment by alexandre-merle** [comment]
ping

**Comment by alexandre-merle** [comment]
ping

**Review by anurag4DSB — CHANGES_REQUESTED** [review]
Your hashes are right in the respective branches.
Can you follow the short version of the hash here: https://github.com/scality/cloudserver/pull/3294/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23

and 

https://github.com/scality/cloudserver/pull/3295/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23

**Review by anurag4DSB — APPROVED** [review]
I do not see anywhere in guidelines that short hashes is mandatory, hence approving.

**Review by nicolas2bert — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
