### PR TITLE
bugfix: S3C-1506 Upgrade UTAPI dependency

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Upgrade UTAPI dependency.

### CODE REVIEW

**Review by philipyoo — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e help

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e approve

**Comment by bennettbuchanan** [comment]
@bert-e status

**Comment by rahulreddy** [comment]
@bert-e bypass_build_status

**Comment by bennettbuchanan** [comment]
@bert-e status

**Comment by rahulreddy** [comment]
@bert-e bypass_jira_check

**Pull request merged**
