### PR TITLE
bugfix: CLDSRV-282 handle object lock when creating a bucket

### PR DESCRIPTION
**Pull request by miniscruff**
* auth results can be an array of arrays
* Object.assign needs an empty object or it modifies the original
* should be `_isObjectLockEnabled` not `!_isObjectLockEnabled`
* add unit tests

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM!

**Comment by ghost** [comment]
If you need to release the project, feel free to bump the project version, as I am not planning to merge my PR this week :smile:

**Comment by miniscruff** [comment]
I will add the bump in the morning, good call

**Review by alexanderchan-scality — APPROVED** [review]

**Pull request merged**
