### PR TITLE
CLDSRV-409: use latest s3cmd with python3

### PR DESCRIPTION
**Pull request by ghost**
Fixes the CI, as python 2.7 is now removed from the action installing it. Instead of keeping old code, let's take advantage of the situation and upgrade everything.

This requires some minor updates in the test suite as the s3cmd output format changed a bit.

### CODE REVIEW

**Comment by williamlardier** [comment]
ping

**Review by anurag4DSB — APPROVED** [review]

**Review by welansari — APPROVED** [review]

**Pull request merged**
