### PR TITLE
bf: ZENKOIO 20 update aws sdk

### PR DESCRIPTION
**Pull request by dora-korpar**
Update aws sdk module to 2.178.0

### CODE REVIEW

**Review by naren-rajendran — APPROVED** [review]

**Review by rahulreddy — CHANGES_REQUESTED** [review]
@dora-korpar This PR is reverting a lot of dependencies in yarn.lock, also can you please target the PR to 7.4 branch?

**Comment by dora-korpar** [comment]
@rahulreddy I retargeted the PR, and the newly generated yarn.lock file looks like it's only upgrading dependencies.

**Comment by dora-korpar** [comment]
@bert-e reset

**Review by anurag4DSB — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by dora-korpar** [comment]
@berte force_reset

**Comment by dora-korpar** [comment]
@bert-e force_reset

**Comment by dora-korpar** [comment]
@bert-e approve

**Pull request merged**
