### PR TITLE
ft: S3C-3040 add object lock actions to bucket policy

### PR DESCRIPTION
**Pull request by ilkescality**
Adds object lock API actions to bucket policy.

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]
LGTM, but let's wait till https://github.com/scality/cloudserver/pull/2634 and https://github.com/scality/cloudserver/pull/2635 are in before we merge this

**Comment by ilkescality** [comment]
@bert-e approve

**Comment by dora-korpar** [comment]
@bert-e wait

**Comment by ilkescality** [comment]
@bert-e help

**Comment by ilkescality** [comment]
@bert-e  wit

**Comment by ilkescality** [comment]
@bert-e wait

**Comment by ilkescality** [comment]
@dora-korpar I initiated the approve just a second before seeing your comment but I think wait worked :)

**Pull request merged**
