### PR TITLE
bugfix: S3C-3904: better s3 action logs

### PR DESCRIPTION
**Pull request by alexandre-merle**
# Description

Improve s3 actions logs by using an override
from arsenal

# Related issues

S3C-3904

### CODE REVIEW

**Comment by alexandre-merle** [comment]
ping

**Comment by alexandre-merle** [comment]
ping

**Review by miniscruff — APPROVED** [review]

**Comment by alexandre-merle** [comment]
@bert-e reset

**Comment by alexandre-merle** [comment]
@bert-e help

**Comment by alexandre-merle** [comment]
@bert-e clear

**Comment by alexandre-merle** [comment]
@bert-e force_reset

**Comment by alexandre-merle** [comment]
ping

**Comment by alexandre-merle** [comment]
ping

**Review by naren-rajendran — APPROVED** [review]

**Pull request merged**
