### PR TITLE
bf(ZENKO-1511): Update Ceph CI Image

### PR DESCRIPTION
**Pull request by tmacro**
Update the path to the `entrypoint.sh` script
`/entrypoint.sh` -> `/opt/ceph-container/bin/entrypoint.sh`

### CODE REVIEW

**Comment by tmacro** [comment]
@bert-e approve

**Review by ssalaues — APPROVED** [review]

**Review by philipyoo — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Review by tcarmet — CHANGES_REQUESTED** [review]
Could you please set the tag of the image that you're using here?
https://github.com/scality/cloudserver/blob/0f0b25584d6f297e7dfe9e95a35b74293aa9f3eb/eve/workers/ceph/Dockerfile#L1

Otherwise you'll face another issue like this one in the future.

**Comment by tmacro** [comment]
So I've pinned it to 3.2.1 Mimic which is the latest stable, however this images is old enough for `entrypoint.sh` not to have moved so I've commented out the other change. When ceph builds 3.2.2's image it will probably change again.

**Review by tcarmet — APPROVED** [review]

**Comment by tcarmet** [comment]
Perfect. Thanks @tmacro

**Review by anurag4DSB — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Pull request merged**
