### PR TITLE
Improvement/cldsrv 474 fix multi object delete api aut

### PR DESCRIPTION
**Pull request by benzekrimaha**
This PR is aiming to fix the multiObjectDelete function due to the crash in the ticket  : 
https://scality.atlassian.net/browse/CLDSRV-474

CI fixes have been introduced in this PR in a separate commit.
The context of the fail : 
- The docker server version was no longer compatible with the docker-compose version installed.
The changes introduced : 
- Using the most recent version of docker compose that comes installed with docker,  changing the command `docker-compose` to `docker compose`

**As this PR is addressing a fix I didn't bump a new version. please let me know if this should be done**
_For integration branches , reviews on the 8.6 and 8.8 are appreciated as more fixups were done in these branches due to differences between 7.x and 8.x_

### CODE REVIEW

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
@bert-e create_integration_branches

**Comment by benzekrimaha** [comment]
@bert-e reset

**Comment by benzekrimaha** [comment]
@bert-e force_reset

**Comment by benzekrimaha** [comment]
@bert-e create_integration_branches

**Comment by benzekrimaha** [comment]
@bert-e reset

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
ping

**Comment by benzekrimaha** [comment]
@bert-e create_pull_requests

**Review by tmacro — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by benzekrimaha** [comment]
@bert-e approve

**Pull request merged**
