### PR TITLE
FIX: S3C-1105 Add env variable modify client port for testing

### PR DESCRIPTION
**Pull request by nicolas2bert**
Running functional tests on a different port (S3 with Nginx on top for example).

### CODE REVIEW

**Comment by LaurenSpiegel** [comment]
what was motivation for this?

**Comment by nicolas2bert** [comment]
@LaurenSpiegel, Vianney needed an environment variable to run functional tests on a different port (S3 with Nginx on top for example).

**Comment by dora-korpar** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by nicolas2bert** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
Closing, please re-open if appropriate.

**Pull request closed without merging**
