### PR TITLE
improvement/S3C-2365 install yarn frozen lockfile

### PR DESCRIPTION
**Pull request by Katherinelaue1**
**What does this PR do, and why do we need it?**
Migrate package manager to yarn frozen lockfile

**Which issue does this PR fix?**
fixes #S3C-2365

**Special notes for your reviewers:**

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e status

**Comment by Katherinelaue1** [comment]
test

**Comment by anurag4DSB** [comment]
@bert-e force_reset

**Comment by anurag4DSB** [comment]
ping

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Review by rahulreddy — APPROVED** [review]
Are you sure that `True` is not needed and lowercase works?

**Review by tmacro — APPROVED** [review]

**Comment by tmacro** [comment]
@rahulreddy YAML supports `true` `True` `yes` and `on` for truthy booleans

**Comment by rahulreddy** [comment]
We had some issues with how python was parsing the yaml and interpreting the truthy values.

**Comment by anurag4DSB** [comment]
"True" was changed to "true"
as the build gave linting errors.

**Comment by anurag4DSB** [comment]
@bert-e ping

**Comment by anurag4DSB** [comment]
ping

**Pull request merged**
