### PR TITLE
improvement: CLDSRV-235-bump-package.json-to-v7.70.0

### PR DESCRIPTION
**Pull request by anurag4DSB**
Bumps package.json to 7.70.0.
The branch development/7.70 and this version is meant for RING 9.1

### CODE REVIEW

**Comment by anurag4DSB** [comment]
ping

**Comment by anurag4DSB** [comment]
ping

**Comment by anurag4DSB** [comment]
ping

**Review by KillianG — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by anurag4DSB** [comment]
PING

**Comment by anurag4DSB** [comment]
ping

**Pull request merged**
