### PR TITLE
ft: ZENKO-413 add GCP support virtual hosts url

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
older pr:  #1255

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@bert-e restart

**Comment by alexanderchan-scality** [comment]
@bert-e help

**Comment by alexanderchan-scality** [comment]
@bert-e reset

**Comment by alexanderchan-scality** [comment]
@bert-e force_reset

**Review by rahulreddy — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e status

**Pull request merged**
