### PR TITLE
CLDSRV-396 putMetadata API route is not updating null version properly

### PR DESCRIPTION
**Pull request by nicolas2bert**
Back-porting and adapting CLDSRV-374 into S3C branches

### CODE REVIEW

**Comment by nicolas2bert** [comment]
ping

**Review by jonathan-gramain — APPROVED** [review]

**Review by welansari — APPROVED** [review]

**Comment by nicolas2bert** [comment]
ping

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by nicolas2bert** [comment]
ping

**Comment by nicolas2bert** [comment]
ping

**Pull request merged**
