### PR TITLE
ft: S3C-2802 add func test for head obj header

### PR DESCRIPTION
**Pull request by ilkescality**
Adds functional test to verify HEAD Object returns `Accept-Ranges` header, as well as a minor cleanup.

### CODE REVIEW

**Review by miniscruff — APPROVED** [review]

**Review by naren-rajendran — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Comment by ilkescality** [comment]
@bert-e approve

**Comment by ilkescality** [comment]
@bert-e wait

**Pull request closed without merging**
