### PR TITLE
bf: remove redundant bucketfile backend (in arsenal)

### PR DESCRIPTION
**Pull request by JianqinWang**
Unused file

### CODE REVIEW

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by JianqinWang** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Pull request closed without merging**
