### PR TITLE
CLDSRV-231 location type DMF prevents cloudserver from starting

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by rachedbenmustapha — COMMENTED** [review]
I'm wondering if this has the side effect of allowing creation of a replication workflow to dmf?

**Comment by nicolas2bert** [comment]
Yes, [This PR](https://github.com/scality/zenko-operator/pull/311) allows dmf locations to be part of the replicationEndpoints list which allows the creation of replication workflow to a DMF location. (c.f. https://github.com/scality/Arsenal/blob/development/8.1/lib/models/ReplicationConfiguration.ts#L358)
We might later use replication to a cold location (different from tiering) so I would add a provisional explicit knob that checks `location.type !== 'dmf'` until we implement replication to DMF.

**Comment by nicolas2bert** [comment]
@RachedBenMustapha Put bucket replication to dmf is not supported: https://github.com/scality/Arsenal/pull/1946

**Review by naren-rajendran — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
