### PR TITLE
bf(S3C-4610): Add missing content-length header to utapi util

### PR DESCRIPTION
**Pull request by tmacro**

### CODE REVIEW

**Review by miniscruff — CHANGES_REQUESTED** [review]
bugfix without a test change?

**Review by jonathan-gramain — APPROVED** [review]

**Comment by tmacro** [comment]
@miniscruff This script currently doesn't have any tests, and standing them up would require a lot of extra time/resources. I have tested the change manually and it has also been verified in the field.

**Review by miniscruff — APPROVED** [review]

**Pull request merged**
