### PR TITLE
Port dev/6.4 to dev/7.4 and fix dependencies

### PR DESCRIPTION
**Pull request by ghost**
Get back on a full 6.4->7.4->8.0 aligned setup for Bert-E

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
done !

**Review by alxf — APPROVED** [review]

**Comment by tcarmet** [comment]
Test succeeded after 4 retry I think.

Adding a bert-E wait on this PR until @rahulreddy and @JianqinWang checked out the work here (There's a PR that looks a lot like this one ;) )

Feel free to delete my bert-e wait command if everything looks good for you!

**Comment by tcarmet** [comment]
@bert-e wait

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
Thanks @DavidPineauScality  and @tcarmet . This is a good start, we will bump up the hashes if needed.

**Pull request merged**
