### PR TITLE
Improvement/cldsrv 327 cloudserver metrics

### PR DESCRIPTION
**Pull request by naren-rajendran**
Cloudserver metrics port from 8.x

### CODE REVIEW

**Review by tmacro — APPROVED** [review]

**Review by nicolas2bert — APPROVED** [review]

**Comment by francoisferrand** [comment]
Looks good overall, but looking at the commits it seems to be some sort of "rewrite" of the same code from 8.x branches : it would have been better to use git cherry-pick, so that it is both easy to see what is going on (what is backport vs what is "new" change needed on 7.x) and to avoid merge conflicts (may not avoid all conflicts, but it helps)...

**Comment by naren-rajendran** [comment]
> Looks good overall, but looking at the commits it seems to be some sort of "rewrite" of the same code from 8.x branches : it would have been better to use git cherry-pick, so that it is both easy to see what is going on (what is backport vs what is "new" change needed on 7.x) and to avoid merge conflicts (may not avoid all conflicts, but it helps)...

I wanted to, but the cherry-picking over a lot of commits done over a good period of time was not helping, so decided to apply them manually.

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Pull request merged**
