### PR TITLE
FIX: CI processMPUParts - too many logs

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Moved the MPU_TESTING setting output out of the loops

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by rahulreddy** [comment]
@ironman-machine r+

**Comment by rahulreddy** [comment]
Closing in favor of https://github.com/scality/cloudserver/pull/1698

**Pull request closed without merging**
