### PR TITLE
 ZENKO-1840 Secure MongoDb access

### PR DESCRIPTION
**Pull request by nicolas2bert**
Support mongo username/password in CloudServer as environment variables

Related to: https://github.com/scality/Arsenal/pull/811

### CODE REVIEW

**Review by alexanderchan-scality — APPROVED** [review]

**Review by ssalaues — APPROVED** [review]
Should this go into 8.0?

**Comment by rahulreddy** [comment]
I think 8.1 is fine as it's a feature.

**Review by rahulreddy — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e aprove

**Comment by nicolas2bert** [comment]
@bert-e approve

**Pull request merged**
