### PR TITLE
FT S3C-1115: GCP S3 Functional Tests: copy

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Adds GCP functional tests for COPY method.

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@ironman-machine clean_env

**Comment by alexanderchan-scality** [comment]
@ironman-machine DEFAULT_BRANCH=rel/7.4-beta
try

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by alexanderchan-scality** [comment]
@ironman-machine try

**Comment by alexanderchan-scality** [comment]
@ironman-machine DEFAULT_BRANCH=rel/7.4-beta
SCALITY_INTEGRATION_BRANCH=rel/7.4-beta
SCALITY_FEDERATION_BRANCH=rel/7.4-beta
RUN_BACKBEAT_CRR_TESTS=true
try

**Comment by rahulreddy** [comment]
Closing in favor of https://github.com/scality/cloudserver/pull/1700

**Pull request closed without merging**
