### PR TITLE
bf: S3C-2880 update aws-sdk

### PR DESCRIPTION
**Pull request by dora-korpar**
First commit: Update aws-sdk to the version that includes Object Lock functionality. There was a conflict with the bluebird module on upgrading, so includes a workaround for that (Async -> Promise)
Second commit: updating aws-sdk caused some tests to fail with unexpected errors, so those tests were moved to either the s3curl or rawnode test suites to confirm correct error returns.

### CODE REVIEW

**Review by rahulreddy — DISMISSED** [review]
Love the diff ❤️

**Review by ilkescality — APPROVED** [review]

**Comment by dora-korpar** [comment]
package.json added 🤦 must've gotten lost in the squash or something

**Comment by rahulreddy** [comment]
> package.json added 🤦 must've gotten lost in the squash or something

Have you tried the latest version `2.672.0` ?

**Comment by dora-korpar** [comment]
> > package.json added 🤦 must've gotten lost in the squash or something
> 
> Have you tried the latest version `2.672.0` ?

Yeah, it doesn't allow promisifying with 'Promise' either :')

**Comment by rahulreddy** [comment]
> > > package.json added 🤦 must've gotten lost in the squash or something
> > 
> > 
> > Have you tried the latest version `2.672.0` ?
> 
> Yeah, it doesn't allow promisifying with 'Promise' either :')

Can you please create a follow up ticket mentioning this.

**Comment by ilkescality** [comment]
> > > package.json added 🤦 must've gotten lost in the squash or something
> > 
> > 
> > Have you tried the latest version `2.672.0` ?
> 
> Yeah, it doesn't allow promisifying with 'Promise' either :')

Ooh interesting!!! So that must the reason WHY it never worked for me (as I was trying everything with the latest version by just conveniently adding `^` 😬)

**Comment by ilkescality** [comment]
> > package.json added 🤦 must've gotten lost in the squash or something
> 
> Have you tried the latest version `2.672.0` ?

@rahulreddy what type of considerations do we have while picking the `sdk` version, or do we usually aim to set it to the latest stable? Assuming it’s the latter (based on you asking about the latest), but I was curious.

**Comment by rahulreddy** [comment]
> > > package.json added 🤦 must've gotten lost in the squash or something
> > 
> > 
> > Have you tried the latest version `2.672.0` ?
> 
> @rahulreddy what type of considerations do we have while picking the `sdk` version, or do we usually aim to set it to the latest stable? Assuming it’s the latter (based on you asking about the latest), but I was curious.

We should shoot for the latest, but make sure pin the version at the same time. The project maintainers should have a task to review the dependencies regularly and update them.

**Comment by dora-korpar** [comment]
@bert-e reset

**Review by miniscruff — APPROVED** [review]

**Comment by dora-korpar** [comment]
@bert-e approve

**Pull request merged**
