### PR TITLE
CLDSRV-57 Artesca 1.3 will only support ingestion from S3C

### PR DESCRIPTION
**Pull request by nicolas2bert**

### CODE REVIEW

**Review by naren-rajendran — APPROVED** [review]

**Review by miniscruff — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]
We can't make zenko 1 releases based on this branch if this is not configurable, but it's probably fine as it wasn't planned.

**Comment by nicolas2bert** [comment]
Yes, let me double check it with @rahulreddy.
Are we planing to use `development/8.3` for Zenko 1.x at some point?

**Review by rahulreddy — APPROVED** [review]

**Comment by nicolas2bert** [comment]
@bert-e approve

**Comment by nicolas2bert** [comment]
Ping

**Pull request merged**
