### PR TITLE
Bugfix/cldsrv 531 delete lifecycle ignored

### PR DESCRIPTION
**Pull request by KazToozs**
# Pull request template

### Motivation and context

Why is this change required? What problem does it solve?

### Related issues

Please use the following link syntaxes #600 to reference issues in the
current repository

### Add tests to cover the changes

New tests added or existing tests modified to cover all changes

### Sign your work

In order to contribute to the project, you must sign your work
https://github.com/scality/Guidelines/blob/master/CONTRIBUTING.md#sign-your-work

Thank you again for contributing! We will try to test and integrate the change
as soon as we can.

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM: I see no specific way to test this as we already added test for this APi in Integration for 9.3, and we do not test authz in s3 (especially in 7.70...)

**Review by fredmnl — APPROVED** [review]

**Review by benzekrimaha — APPROVED** [review]

**Comment by KazToozs** [comment]
ping

**Review by anurag4DSB — APPROVED** [review]

**Pull request merged**
