### PR TITLE
CLDSRV-259: bump arsenal 7.10.31

### PR DESCRIPTION
**Pull request by KillianG**

### CODE REVIEW

**Comment by KillianG** [comment]
ping

**Review by XinLi0207 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by anurag4DSB** [comment]
Why do we have package lock and yarn lock here?

**Comment by anurag4DSB** [comment]
there are multiple issues I see here:

* Introduction of package json lock file when we use yarn
* Introduction of changes in yarn.lock file in integration branches without update of package.json
* Introduction of Arsenal 7.x into cloudserver 8.x yarn.lock file through package.json.lock file
* New changes in ARTESCA/ZENKO were introduced without e2e testing.

Please fix this today ASAP. Let me know if you have any questions regarding these.

**Comment by anurag4DSB** [comment]
Update: 
In ARTESCA we do not use frozen lock option for yarn install.
It seemed to been have removed during typescript migration.

The only issue here  is introduction package-lock.json which will be removed in https://scality.atlassian.net/browse/CLDSRV-260

**Pull request merged**
