### PR TITLE
Port development/6.4 to development/7.4 and fix dependencies

### PR DESCRIPTION
**Pull request by ghost**
Get back on a full 6.4->7.4->8.0 aligned setup for Bert-E

### CODE REVIEW

**Comment by DavidPineauScality** [comment]
ping

**Comment by ghost** [comment]
ping

**Comment by DavidPineauScality** [comment]
@bert-e reset

**Comment by DavidPineauScality** [comment]
... !
@bert-e force_reset

**Comment by DavidPineauScality** [comment]
ping

**Pull request closed without merging**
