### PR TITLE
bugfix(s3-data): add noCache and noSync option

### PR DESCRIPTION
**Pull request by giacope**
This PR allows you to configure the `noCache` and `noSync` options for both `s3-data` and `pfsd` (`pfsd` change is on the integration branch).

See scality/Arsenal#635 for reference.

### CODE REVIEW

**Comment by giacope** [comment]
@bert-e help

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
@bert-e force_reset

**Review by vrancurel — APPROVED** [review]

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
@bert-e force_reset

**Comment by giacope** [comment]
@bert-e force_reset

**Review by JianqinWang — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Comment by giacope** [comment]
@bert-e approve

**Pull request merged**
