### PR TITLE
bugfix: ZENKO-1460 maven fix for ci upgrade

### PR DESCRIPTION
**Pull request by rahulreddy**
bugfix: ZENKO-1460 maven fix for ci upgrade

### CODE REVIEW

**Review by bertranddemiddelaer — APPROVED** [review]
LGTM, as there is the useSystemClassLoader workaround.

**Comment by rahulreddy** [comment]
@bert-e reset

**Comment by rahulreddy** [comment]
Switching to 7.4 as we don't have eve in 6.4

**Comment by rahulreddy** [comment]
@bert-e reset

**Review by anurag4DSB — APPROVED** [review]

**Review by dora-korpar — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Comment by rahulreddy** [comment]
@bert-e approve

**Pull request merged**
