### PR TITLE
CLDSRV-43: add expiration response headers to APIs

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
add expiration response headers to APIs:
* PutObject
* GetObject
* HeadObject
* CopyObject
* ListParts
* InitiateMultipartUploads
* CompleteMultipartUploads

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
ping

**Review by saitharunthodupunuru — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Pull request merged**
