### PR TITLE
bugfix: WebsiteRedirectLocation header response

### PR DESCRIPTION
**Pull request by giacope**
Reopened old PR #1208, now with bert-e.

### CODE REVIEW

**Comment by rahulreddy** [comment]
@bert-e wait

**Comment by rahulreddy** [comment]
@giacomoguiulfo  I changed the base to development/6.4 as it's a bugfix that's relevant to an older branch. Can you rebase your branch?

**Comment by giacomoguiulfo** [comment]
Oops, targeted 6.4 instead of 8.0. Closing this.

**Comment by giacomoguiulfo** [comment]
Oh, GitHub allows retargeting. Too late 😔

**Comment by giacope** [comment]
@rahulreddy Just saw this comment. My bad, I closed this PR thinking it had a bad target, and I didn't know Github allowed retargeting. Reopened in #1366 targeting `development/6.4` with everything properly rebased.

**Pull request closed without merging**
