### PR TITLE
bugfix: S3C-2052 Delete orphaned data

### PR DESCRIPTION
**Pull request by bennettbuchanan**
Forward port of https://github.com/scality/cloudserver/pull/2055 to stabilization branch.

### CODE REVIEW

**Review by anurag4DSB — APPROVED** [review]

**Review by jonathan-gramain — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by bennettbuchanan** [comment]
@bert-e reset

**Comment by bennettbuchanan** [comment]
@bert-e status

**Comment by bennettbuchanan** [comment]
@bert-e reset

**Comment by bennettbuchanan** [comment]
@bert-e approve

**Comment by bennettbuchanan** [comment]
@bert-e status

**Comment by bennettbuchanan** [comment]
@bert-e help

**Comment by bennettbuchanan** [comment]
@bert-e force_reset

**Pull request closed without merging**
