### PR TITLE
CLDSRV-234: bump arsenal

### PR DESCRIPTION
**Pull request by ghost**
To fix [list-object](https://scality.atlassian.net/jira/software/c/projects/OS/boards/214?modal=detail&selectedIssue=ARTESCA-5165) issue

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Please update the yarn lock file as well :slightly_smiling_face:

**Review by anurag4DSB — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Approving but the build issue may need a fix if it's not coming from the scality cloud current load

**Comment by ghost** [comment]
ping

**Comment by ghost** [comment]
ping

**Comment by ghost** [comment]
ping

**Pull request merged**
