### PR TITLE
S3C-1183: GCP Tagging Functional Tests

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
Adds GCP Tagging Functional Test

### CODE REVIEW

**Comment by alexanderchan-scality** [comment]
@ironman-machine 
DEFAULT_BRANCH=rel/7.4-beta
try

**Comment by alexanderchan-scality** [comment]
@ironman-machine clean_env

**Comment by alexanderchan-scality** [comment]
@ironman-machine 
DEFAULT_BRANCH=rel/7.4-beta
try

**Comment by alexanderchan-scality** [comment]
@ironman-machine
DEFAULT_BRANCH=rel/7.4-beta
try

**Comment by alexanderchan-scality** [comment]
passing E2E: http://ci.ironmann.io/gh/scality/Integration/20698

**Comment by alexanderchan-scality** [comment]
@ironman-machine clean_env

**Comment by alexanderchan-scality** [comment]
@ironman-machine DEFAULT_BRANCH=rel/7.4-beta
SCALITY_INTEGRATION_BRANCH=rel/7.4-beta
SCALITY_FEDERATION_BRANCH=rel/7.4-beta
RUN_BACKBEAT_CRR_TESTS=true
try

**Comment by rahulreddy** [comment]
Closing this in favor of https://github.com/scality/cloudserver/pull/1701

**Pull request closed without merging**
