### PR TITLE
bugfix: WebsiteRedirectLocation header response

### PR DESCRIPTION
**Pull request by giacope**
Reopened old PR #1208, now with bert-e.

### CODE REVIEW

**Comment by giacope** [comment]
@bert-e help

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
@bert-e force_reset

**Comment by giacope** [comment]
load

**Comment by giacope** [comment]
load

**Review by dora-korpar — APPROVED** [review]

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
load

**Comment by giacope** [comment]
load

**Review by rahulreddy — APPROVED** [review]

**Comment by tcarmet** [comment]
Hello all!

Really happy to see that you're porting fixes on 6.4 with bert-e!
Although there's a little problem here, you don't have any CI on development/6.4 so your PR will not get merged until you have a green build.
From my point of view you can either:
* Backport the CI code, or a little piece as you don't have all the features/tests in 6.4
* Create a mini CI in 6.4 that perform some very basic operation (like linting) so that you can have your green build to merge this PR.

I'll leave the decision up to you guys!
Good luck

**Comment by rahulreddy** [comment]
Let's not merge this yet. I just got an email today where it was seen as a regression if we changed the behavior without notice, even if it's the right behavior.

**Comment by rahulreddy** [comment]
@bert-e wait

**Comment by harperscality** [comment]
argl @rahulreddy ! Can we merge now ?

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
@bert-e status

**Comment by giacope** [comment]
@bert-e help

**Comment by giacope** [comment]
@bert-e reset

**Comment by giacope** [comment]
@bert-e help

**Comment by giacope** [comment]
@bert-e approve

**Pull request merged**
