### PR TITLE
bf: ZENKO-751 update arsenal package

### PR DESCRIPTION
**Pull request by philipyoo**
object key max size is set to 915

### CODE REVIEW

**Review by JianqinWang — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Review by jonathan-gramain — CHANGES_REQUESTED** [review]
can you revert the unnecessary changes in package-lock.json?

**Comment by philipyoo** [comment]
@jonathan-gramain So I can't say for certain, but seems like there are some known issues with package lock files and how they are generated. But the problems seem to be related to either version differences or OS differences (https://github.com/npm/npm/issues/17749)

I saw sha-512 -> sha-1 changes being made. To fix this, I had to remove my existing node module folder and npm install again.
I wasn't aware the lock file would be affected by the existing node modules dir, especially since my package.json changes were only for arsenal   o.O

**Comment by philipyoo** [comment]
@bert-e reset

**Review by rahulreddy — APPROVED** [review]

**Comment by philipyoo** [comment]
@bert-e reset

**Pull request merged**
