### PR TITLE
cleanup: Remove duplicated code

### PR DESCRIPTION
**Pull request by vrancurel**
Bucketclient and bucketfile seem to be identical to Arsenal.
  We need to keep a dependency on bucket client lib for avoiding
  circular dependency.

### CODE REVIEW

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
We have a reference in `routeMetadata.js` to that BucketClientInterface (not ideal). So on startup this exception is thrown
```js

Error: Cannot find module '../metadata/bucketclient/backend'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rahul/developer/repos/cloudserver/lib/routes/routeMetadata.js:8:31)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/rahul/developer/repos/cloudserver/lib/utilities/internalHandlers.js:3:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
```

**Comment by vrancurel** [comment]
can we change this ?

**Comment by vrancurel** [comment]
@rahulreddy

**Comment by vrancurel** [comment]
I don't understand why the CI is failing

**Review by rahulreddy — APPROVED** [review]

**Review by JianqinWang — APPROVED** [review]

**Pull request merged**
