### PR TITLE
improvement: bump version to 8.2.13

### PR DESCRIPTION
**Pull request by naren-rajendran**
Bump version to 8.2.13.

### CODE REVIEW

**Review by nicolas2bert — APPROVED** [review]

**Review by miniscruff — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Comment by rahulreddy** [comment]
/bypass_build_status
We see tests passing in different builds. The tests are flaky writing to Azure, GCP clouds.

**Comment by naren-rajendran** [comment]
@bert-e approve

**Pull request merged**
