### PR TITLE
Bugfix/cldsrv 10 get acl with predefined groups stabilization

### PR DESCRIPTION
**Pull request by naren-rajendran**

### CODE REVIEW

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Comment by naren-rajendran** [comment]
@bert-e reset

**Review by tmacro — APPROVED** [review]

**Comment by jonathan-gramain** [comment]
@naren-scality please do `git cherry-pick -x` to be able to track the original commit

**Comment by naren-rajendran** [comment]
> @naren-scality please do `git cherry-pick -x` to be able to track the original commit

Yes, the reference is in the commit message, generated by `git cherry-pick -x`

**Comment by jonathan-gramain** [comment]
@naren-scality indeed, my bad

**Review by jonathan-gramain — APPROVED** [review]

**Pull request merged**
