### PR TITLE
Remove default replication endpoint mandate

### PR DESCRIPTION
**Pull request by francoisferrand**
The default replication endpoint should not be needed, esp. since the
one we use (in zenko) does not relate to an existing location: it is
used only to let Cloudserver start.

Issue: CLDSRV-211

### CODE REVIEW

**Review by nicolas2bert — COMMENTED** [review]
From what I remember the default replication endpoint was there because:
When putBucketReplication, we specify the following parameters:
```
{
      Bucket: 'your source bucket',
      ReplicationConfiguration: {
        Role: 'roleArn',
        Rules: [{
          Destination: {StorageClass: "destination location", Bucket: "prefix of destination bucket"},
          Prefix: '',
          Status: 'Enabled',
        }],
      },
    }
```
From S3 documentation, “Rule.Destination.StorageClass” is optional, however, this information is key in the replication logic (shows in which location we replicate the objects).
If it is not provided, we use the site mentioned in replicationEndpoints with .default === true

**Comment by francoisferrand** [comment]
> If it is not provided, we use the site mentioned in replicationEndpoints with .default === true

indeed, this is the code I changed in this PR.
we used to require a "default" replicationEndpoint, but ended up just creating a dummy one to make cloudserver start (and I could not get better explanation). So I updated the logic so that, when there is no explicit endpoint, we take:
* the one marked as `.default === true`, if any
* else the first one
* else return an error

**Review by miniscruff — APPROVED** [review]
I agree the the code does what the comment says, but can not say myself if this is the right approach. I would like a test if possible either way.

**Review by rachedbenmustapha — APPROVED** [review]
The change seems to make sense, but I can't be sure that no regression will come from it.

**Review by nicolas2bert — APPROVED** [review]

**Pull request merged**
