### PR TITLE
Feature/zenko 3368/add chain backend

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
* add the use of chain auth backend when `S3VAULT` is set to `multiple`
  * allows for authentication to be done against a list of backends/clients

### CODE REVIEW

**Review by naren-rajendran — APPROVED** [review]

**Review by rachedbenmustapha — APPROVED** [review]

**Comment by rachedbenmustapha** [comment]
seen with @alexanderchan-scality - both test failures are cloud provider flakiness, so forced bert-e merge.

**Pull request merged**
