### PR TITLE
bugfix/ZENKO-436 retrieve correct read location constraint

### PR DESCRIPTION
**Pull request by alexanderchan-scality**
(cherry picked from commit b7fb3797030f229a6d3b04db82fc6657dcc753ed)
+ some typo fixes

older pr: #1264

### CODE REVIEW

**Review by jonathan-gramain — DISMISSED** [review]

**Review by rahulreddy — DISMISSED** [review]

**Review by rahulreddy — DISMISSED** [review]

**Review by jonathan-gramain — DISMISSED** [review]

**Comment by rahulreddy** [comment]
@bert-e help

**Comment by rahulreddy** [comment]
@bert-e help

**Comment by alexanderchan-scality** [comment]
@bert-e help

**Comment by rahulreddy** [comment]
@bert-e reset

**Comment by rahulreddy** [comment]
@bert-e build

**Comment by rahulreddy** [comment]
@bert-e bypass_jira_check

**Comment by rahulreddy** [comment]
@bert-e clear

**Comment by alexanderchan-scality** [comment]
@bert-e force_reset

**Review by giacope — APPROVED** [review]

**Pull request merged**
